spring: 
   datasource:
      username: bobbin_lace
      password: bobbin_lace
      url: jdbc:mysql://localhost:3306/bobbin_lace
      
   jpa: 
      hibernate:
         ddl-auto: update 
      show-sql: true
      
   sql:
       init:
          mode: never
          